{
  "author_association": "OWNER", 
  "body": "@djw8605: I've tested this and see the expected behavior:\n1. Without the `--debug` flag, the exception is output to a file but hidden from stdout.\n2. With `--debug` specified, the exception is printed to stdout as well as to the `.stack*` file.\n\nCould you review this change? \n", 
  "created_at": "2016-05-25T21:13:18Z", 
  "html_url": "https://github.com/opensciencegrid/htcondor-ce/pull/96#issuecomment-221709379", 
  "id": 221709379, 
  "issue_url": "https://api.github.com/repos/opensciencegrid/htcondor-ce/issues/96", 
  "updated_at": "2016-05-25T21:13:18Z", 
  "url": "https://api.github.com/repos/opensciencegrid/htcondor-ce/issues/comments/221709379", 
  "user": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/390105?v=4", 
    "events_url": "https://api.github.com/users/brianhlin/events{/privacy}", 
    "followers_url": "https://api.github.com/users/brianhlin/followers", 
    "following_url": "https://api.github.com/users/brianhlin/following{/other_user}", 
    "gists_url": "https://api.github.com/users/brianhlin/gists{/gist_id}", 
    "gravatar_id": "", 
    "html_url": "https://github.com/brianhlin", 
    "id": 390105, 
    "login": "brianhlin", 
    "organizations_url": "https://api.github.com/users/brianhlin/orgs", 
    "received_events_url": "https://api.github.com/users/brianhlin/received_events", 
    "repos_url": "https://api.github.com/users/brianhlin/repos", 
    "site_admin": false, 
    "starred_url": "https://api.github.com/users/brianhlin/starred{/owner}{/repo}", 
    "subscriptions_url": "https://api.github.com/users/brianhlin/subscriptions", 
    "type": "User", 
    "url": "https://api.github.com/users/brianhlin"
  }
}
